<a href="https://colab.research.google.com/github/RuiRodrigues-lab/DataScienceFE/blob/Locker/CP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
from pandas.api.types import CategoricalDtype
import numpy as np
import matplotlib.pyplot as plt
#Precisamos desta biblioteca para podermos escolher um ficheiro local
#Se o ficheiro vier por API ou tivermos um link, é so alterar a forma de import
from google.colab import files

# 1️⃣ Faz upload do ficheiro (vai abrir uma janela para escolher no teu PC)
uploaded = files.upload()

# 2️⃣ Guarda o nome do ficheiro (Colab mostra o nome depois do upload)
filename = list(uploaded.keys())[0]

# 3️⃣ Lê o Excel, por default lê sempre a primeira tab, por isso podemos usar o "sheet_name"
# Se tivermos dados em varias tabs, devemos usar uma Dataframe(df) para cada uma das tabs
df = pd.read_excel(filename, sheet_name='Dados')
df.head()

Saving CP3.xlsx to CP3 (2).xlsx

        Sexo Transporte   SatisfacaoCurso  Idade  NotaFinal
0  Masculino         Pé  Muito Satisfeito     22       17.7
1  Masculino      Carro      Insatisfeito     20       13.4
2   Feminino  Bicicleta  Muito Satisfeito     22       12.9
3  Masculino  Bicicleta      Insatisfeito     21       11.6
4  Masculino  Bicicleta      Insatisfeito     22       10.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sexo             30 non-null     object
 1   Transporte       30 non-null     object
 2   SatisfacaoCurso  30 non-null     object
 3   Idade            30 non-null     int64
 4   NotaFinal        30 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.3+ KB

In [7]:
linhas, colunas = df.shape
print("Número de linhas:", linhas)
print("Número de colunas:", colunas)

num_cols = ['Idade', 'NotaFinal']

# Estatísticas principais
desc = df[num_cols].agg(['count', 'mean', 'median', 'std', 'min', 'max', 'skew', 'kurtosis']).T

# Quartis (Q1, Q3) + Range
desc['Q1'] = df[num_cols].quantile(0.25)
desc['Q2'] = df[num_cols].quantile(0.50)  # mediana, só para consistência
desc['Q3'] = df[num_cols].quantile(0.75)
desc['Range'] = desc['max'] - desc['min']

# Arredondar e reordenar colunas
desc = desc[['count', 'mean', 'std', 'min', 'Q1', 'Q2', 'Q3', 'max', 'Range', 'skew', 'kurtosis']].round(3)

desc

Número de linhas: 30
Número de colunas: 5

,count,mean,std,min,Q1,Q2,Q3,max,Range,skew,kurtosis
Idade,30.0,20.300,1.535,18.0,19.0,21.0,22.000,22.0,4.0,-0.361,-1.378
NotaFinal,30.0,15.113,3.100,10.0,12.4,15.1,17.675,19.9,9.9,0.025,-1.356

In [20]:
# 🔹 Variáveis nominais: Sexo
cols_nominais = ['Sexo']
df[cols_nominais] = df[cols_nominais].astype('category')

# 🔹 Variável ordinal: Transporte (ordem definida manualmente)
transport_levels = ['Pé', 'Bicicleta', 'Autocarro', 'Carro']
transport_type = CategoricalDtype(categories=transport_levels, ordered=True)
df['Transporte'] = df['Transporte'].astype(transport_type)

# 🔹 Variável ordinal: SatisfacaoCurso, se quiseres já definir a ordem
satisf_levels = ['Muito Insatisfeito', 'Insatisfeito', 'Pouco Satisfeito', 'Satisfeito', 'Muito Satisfeito']
satisf_type = CategoricalDtype(categories=satisf_levels, ordered=True)
df['SatisfacaoCurso'] = df['SatisfacaoCurso'].astype(satisf_type)

#Para vermos se ficou tudo bem, definimos esta função
def glimpse(df):
    print(f"📊 DataFrame com {df.shape[0]} linhas e {df.shape[1]} colunas\n")
    for col in df.columns:
        dtype = df[col].dtype
        preview = df[col].unique()[:5]  # mostra até 5 valores únicos
        print(f"{col:<15} ({dtype})  →  {preview}")

#print
glimpse(df)

📊 DataFrame com 30 linhas e 5 colunas

Sexo            (category)  →  ['Masculino', 'Feminino']
Categories (2, object): ['Feminino', 'Masculino']
Transporte      (category)  →  ['Pé', 'Carro', 'Bicicleta', 'Autocarro']
Categories (4, object): ['Pé' < 'Bicicleta' < 'Autocarro' < 'Carro']
SatisfacaoCurso (category)  →  ['Muito Satisfeito', 'Insatisfeito', 'Satisfeito', 'Pouco Satisfeito', 'Muito Insatisfeito']
Categories (5, object): ['Muito Insatisfeito' < 'Insatisfeito' < 'Pouco Satisfeito' < 'Satisfeito' <
                         'Muito Satisfeito']
Idade           (int64)  →  [22 20 21 19 18]
NotaFinal       (float64)  →  [17.7 13.4 12.9 11.6 10. ]