<a href="https://colab.research.google.com/github/RuiRodrigues-lab/DataScienceFE/blob/Locker/FreqRltvAbsol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importar a lib como pd e np
import pandas as pd
import numpy as np

In [ ]:
#Aqui definimos os dados da amostra test
dados = {
    "Grau_Escolaridade": (
        ["Básico"] * 3 +
        ["Secundário"] * 5 +
        ["Licenciatura"] * 13 +
        ["Mestrado"] * 4
    )
}

df = pd.DataFrame(dados)
df.head()

  Grau_Escolaridade
0            Básico
1            Básico
2            Básico
3        Secundário
4        Secundário

In [ ]:
#Frequencias Absolutas
freq_abs = df["Grau_Escolaridade"].value_counts()
freq_abs

Grau_Escolaridade
Licenciatura    13
Secundário       5
Mestrado         4
Básico           3
Name: count, dtype: int64

In [ ]:
#Frequencias Relativas
freq_rel = df["Grau_Escolaridade"].value_counts(normalize=True).round(2)
freq_rel

Grau_Escolaridade
Licenciatura    0.52
Secundário      0.20
Mestrado        0.16
Básico          0.12
Name: proportion, dtype: float64

In [ ]:
#Aqui juntamos ambas as columas que calculamos antes em uma tabela
tabela = pd.DataFrame({
    "Frequência": freq_abs,
    "Frequência Relativa": freq_rel
})
tabela

                   Frequência  Frequência Relativa
Grau_Escolaridade
Licenciatura               13                 0.52
Secundário                  5                 0.20
Mestrado                    4                 0.16
Básico                      3                 0.12

In [ ]:
# Moda (pode devolver várias em caso de empate)
moda = df["Grau_Escolaridade"].mode()
print("Moda:", list(moda))

# Frequência da(s) moda(s) e percentagem
vc = df["Grau_Escolaridade"].value_counts()
freq_max = vc.max()
modas = vc[vc == freq_max]
print(" ")
print("Frequências da(s) moda(s):")
print(modas)
print(" ")
print("Percentagem:", freq_max / len(df))

Moda: ['Licenciatura']

Frequências da(s) moda(s):
Grau_Escolaridade
Licenciatura    13
Name: count, dtype: int64

Percentagem: 0.52