In [1]:
#importar a lib como pd 
import pandas as pd

In [2]:
#Aqui definimos os dados da amostra
dados = {
    "Grau_Escolaridade": (
        ["Básico"] * 3 +
        ["Secundário"] * 5 +
        ["Licenciatura"] * 13 +
        ["Mestrado"] * 4
    )
}

df = pd.DataFrame(dados)
df.head()

  Grau_Escolaridade
0            Básico
1            Básico
2            Básico
3        Secundário
4        Secundário

In [3]:
#Frequencias Absolutas
freq_abs = df["Grau_Escolaridade"].value_counts()
freq_abs

Grau_Escolaridade
Licenciatura    13
Secundário       5
Mestrado         4
Básico           3
Name: count, dtype: int64

In [4]:
#Frequencias Relativas
freq_rel = df["Grau_Escolaridade"].value_counts(normalize=True).round(2)
freq_rel

Grau_Escolaridade
Licenciatura    0.52
Secundário      0.20
Mestrado        0.16
Básico          0.12
Name: proportion, dtype: float64

In [5]:
#Aqui juntamos ambas as columas que calculamos antes em uma tabela
tabela = pd.DataFrame({
    "Frequência": freq_abs,
    "Frequência Relativa": freq_rel
})
tabela

                   Frequência  Frequência Relativa
Grau_Escolaridade
Licenciatura               13                 0.52
Secundário                  5                 0.20
Mestrado                    4                 0.16
Básico                      3                 0.12